package com.quetoquenana.pedalpal.bike.domain.model;

public enum BikeField {
    BIKE_NAME,
    BIKE_TYPE,
    BIKE_IS_PUBLIC,
    BIKE_IS_EXTERNAL_SYNC,
    BIKE_STATUS,
    BIKE_BRAND,
    BIKE_MODEL,
    BIKE_YEAR,
    BIKE_SERIAL_NUMBER,
    BIKE_NOTES,
    BIKE_ODOMETER,
    BIKE_USAGE_MINUTES,
    BIKE_COMPONENT,
    BIKE_COMPONENT_TYPE,
    BIKE_COMPONENT_NAME,
    BIKE_COMPONENT_BRAND,
    BIKE_COMPONENT_MODEL,
    BIKE_COMPONENT_STATUS,
    BIKE_COMPONENT_NOTES,
    BIKE_COMPONENT_ODOMETER,
    BIKE_COMPONENT_USAGE_MINUTES
}
