CREATE TABLE system_codes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category varchar NOT NULL,
    code varchar NOT NULL,
    label varchar,
    description varchar,
    is_active boolean DEFAULT true,
    code_key varchar,
    position int,

    CONSTRAINT ux_system_codes_category_code UNIQUE (category, code)
);

INSERT INTO system_codes (category, code, label, description, is_active, code_key, position) VALUES
 ('APPOINTMENT_STATUS', 'CREATED', 'Created', 'Appointment created, need to be confirmed', true, 'appointment.status.created', 1),
 ('APPOINTMENT_STATUS', 'CONFIRMED', 'Confirmed', 'Appointment is confirmed', true, 'appointment.status.confirmed', 2),
 ('APPOINTMENT_STATUS', 'IN_PROGRESS', 'In Progress', 'In progress', true, 'appointment.status.in.progress', 3),
 ('APPOINTMENT_STATUS', 'COMPLETED', 'Completed', 'Completed', true, 'appointment.status.completed', 4),
 ('APPOINTMENT_STATUS', 'CANCELLED', 'Cancelled', 'Cancelled', true, 'appointment.status.cancelled', 5),
 ('APPOINTMENT_STATUS', 'NO_SHOW', 'No Show', 'No show', true, 'appointment.status.no.show', 6),
 ('BIKE_TYPE', 'ROAD', 'Road', 'Road bike', true, 'bike.type.road', 1),
 ('BIKE_TYPE', 'MOUNTAIN', 'Mountain', 'Mountain bike', true, 'bike.type.mtb', 2),
 ('BIKE_TYPE', 'HYBRID', 'Hybrid', 'Hybrid bike', true, 'bike.type.hybrid', 3),
 ('BIKE_TYPE', 'GRAVEL', 'Gravel', 'Gravel bike', true, 'bike.type.gravel', 4),
 ('BIKE_TYPE', 'ELECTRIC', 'Electric', 'Electric bike (e-bike)', true, 'bike.type.electric', 5),
 ('BIKE_TYPE', 'URBAN', 'Urban', 'Urban/City bike', true, 'bike.type.urban', 6),
 ('COMPONENT_TYPE', 'CHAIN', 'Chain', 'Chain', true, 'component.chain', 1),
 ('COMPONENT_TYPE', 'CASSETTE', 'Cassette', 'Cassette', true, 'component.cassette', 2),
 ('COMPONENT_TYPE', 'CHAINRINGS', 'Chainrings', 'Chainrings', true, 'component.chainrings', 3),
 ('COMPONENT_TYPE', 'DERAILLEUR_FRONT', 'Front derailleur', 'Front derailleur', true, 'component.derailleur.front', 4),
 ('COMPONENT_TYPE', 'DERAILLEUR_REAR', 'Rear derailleur', 'Rear derailleur', true, 'component.derailleur.rear', 5),
 ('COMPONENT_TYPE', 'SHIFTERS', 'Shifters', 'Shifters', true, 'component.shifters', 6),
 ('COMPONENT_TYPE', 'BRAKE_PADS', 'Brake pads', 'Brake pads', true, 'component.brake.pads', 7),
 ('COMPONENT_TYPE', 'BRAKE_ROTORS', 'Brake rotors', 'Brake rotors', true, 'component.brake.rotors', 8),
 ('COMPONENT_TYPE', 'BRAKE_CALIPERS', 'Brake calipers', 'Brake calipers', true, 'component.brake.calipers', 9),
 ('COMPONENT_TYPE', 'TIRES', 'Tires', 'Tires', true, 'component.tires', 10),
 ('COMPONENT_TYPE', 'TUBES', 'Tubes', 'Tubes', true, 'component.tubes', 11),
 ('COMPONENT_TYPE', 'SEALANT', 'Sealant', 'Sealant', true, 'component.sealant', 12),
 ('COMPONENT_TYPE', 'RIMS', 'Rims', 'Rims', true, 'component.rims', 13),
 ('COMPONENT_TYPE', 'SPOKES', 'Spokes', 'Spokes', true, 'component.spokes', 14),
 ('COMPONENT_TYPE', 'BOTTOM_BRACKET', 'Bottom bracket', 'Bottom bracket', true, 'component.bottom.bracket', 15),
 ('COMPONENT_TYPE', 'HEADSET', 'Headset', 'Headset', true, 'component.headset', 16),
 ('COMPONENT_TYPE', 'HUBS', 'Hubs', 'Hubs', true, 'component.hubs', 17),
 ('COMPONENT_TYPE', 'BEARINGS', 'Bearings', 'Bearings', true, 'component.bearings', 18),
 ('COMPONENT_TYPE', 'SADDLE', 'Saddle', 'Saddle', true, 'component.saddle', 19),
 ('COMPONENT_TYPE', 'SEAT_POST', 'Seat post', 'Seat post', true, 'component.seat.post', 20),
 ('COMPONENT_TYPE', 'HANDLEBAR', 'Handlebar', 'Handlebar', true, 'component.handlebar', 21),
 ('COMPONENT_TYPE', 'STEM', 'Stem', 'Stem', true, 'component.stem', 22),
 ('COMPONENT_TYPE', 'GRIPS', 'Grips', 'Grips', true, 'component.grips', 23),
 ('COMPONENT_TYPE', 'BAR_TAPE', 'Bar tape', 'Bar tape', true, 'component.bar.tape', 24),
 ('COMPONENT_TYPE', 'PEDALS', 'Pedals', 'Pedals', true, 'component.pedals', 25),
 ('COMPONENT_TYPE', 'FORK', 'Fork', 'Fork', true, 'component.fork', 26),
 ('COMPONENT_TYPE', 'REAR_SHOCK', 'Rear shock', 'Rear shock', true, 'component.rear.shock', 27),
 ('COMPONENT_TYPE', 'BATTERY', 'Battery', 'Battery', true, 'component.battery', 28),
 ('COMPONENT_TYPE', 'MOTOR', 'Motor', 'Motor', true, 'component.motor', 29),
 ('COMPONENT_TYPE', 'CONTROLLER', 'Controller', 'Controller', true, 'component.controller', 30),
 ('COMPONENT_TYPE', 'OTHER', 'Other', 'Other', true, 'component.other', 31)
 ;

